# Generated by Django 6.1 on 2026-08-10 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('capacity', models.CharField(max_length=100)),
                ('useCase', models.CharField(max_length=100)),
                ('theme', models.CharField(choices=[('blue', 'Blue Theme'), ('purple', 'Purple Theme'), ('green', 'Green Theme')], default='blue', max_length=50)),
                ('imageUrl', models.URLField(blank=True, max_length=1000, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
